### ISSUE TITLE
Зауваження до записки

### ISSUE THREAD

**Issue by BrunIF** [happytomatoe/Quicktour#1]
- Подивитись на типові помилки ( https://github.com/ploska4/Dyplom_Project_Parada_I/issues/4#issue-34933743 )
- По тексту зустрічається не однакове форматування (списки то з великої букви починаються, то з малої)
- У другий розділ додайте засоби, технології та інструменти які використовували

Загалом гарна робота. Чекаю виправлень. 
p.s. Поспішіть.

**Comment by happytomatoe** [comment]
Переробив.
огляд технологій описаний в 1 розділі

**Comment by BrunIF** [comment]
1.2 - повністю перенести в 2
1.1 та 1.3 залишити у першому розділі.
